# Site settings
title: The Code Diaries
header-img: img/home-bg.png
email: niquelejon@gmail.com
copyright_name: iamlejon
description: > # this means to ignore newlines until "baseurl:"
  Digital Meltdowns
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  iamlejon
learn_profile: iamlejon
email_username: niquelejon@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
